### ISSUE TITLE
Problems with Websocket requests

### ISSUE THREAD

**Issue by paulfears** [MetaMask/snaps-monorepo#1004]
Not really sure whats going on here
Was trying to use xrpl.js
but anytime it trys to make a websocket request I get this error,
It used to work on older versions of the snaps interface, with an older version of the compiler
Error:
lockdown.umd.min.js:1 Error: Unhandled error. (undefined)
  at Client.emit (eval at <anonymous> (eval at <anonymous> (lockdown.umd.min.js:1:19217)), <anonymous>:29293:21)
  at Connection.eval (eval at <anonymous> (eval at <anonymous> (lockdown.umd.min.js:1:19217)), <anonymous>:43710:18)
  at Connection.emit (eval at <anonymous> (eval at <anonymous> (lockdown.umd.min.js:1:19217)), <anonymous>:29300:11)
  at Connection.onMessage (eval at <anonymous> (eval at <anonymous> (lockdown.umd.min.js:1:19217)), <anonymous>:43450:24)
  at WSWrapper.eval (eval at <anonymous> (eval at <anonymous> (lockdown.umd.min.js:1:19217)), <anonymous>:43486:55)
  at WSWrapper.emit (eval at <anonymous> (eval at <anonymous> (lockdown.umd.min.js:1:19217)), <anonymous>:29300:11)
  at WSWrapper.ws.onmessage (eval at <anonymous> (eval at <anonymous> (lockdown.umd.min.js:1:19217)), <anonymous>:43185:18)
  at WebSocket.<anonymous> (bundle.js:2:717975)

I hate to have so little info, but im kind of at a wall.
-cheers

**Comment by FrederikBolding** [comment]
Hi @paulfears - Do you have the source code available for the snap you are having issues with? That would help us reproduce your issue!

**Comment by paulfears** [comment]
Here's the source code
https://github.com/Kyraview/SnapXrpFork

It's purposely version 20 of snaps because the library requires Buffer, and there's a patches that have to be applied if you guys try to run it.
I appreciate you guys taking time to look at this issue

**Comment by FrederikBolding** [comment]
Which version of Flask are you using? The version from the Chrome Store or building locally from the extension `develop`?

**Comment by FrederikBolding** [comment]
If you are using the Flask version from the Chrome Store, there is a known and fixed bug with WebSocket that will be fixed in the next release! Meanwhile if you are comfortable with it you can build the MetaMask extension locally as that has more recent changes.

**Comment by paulfears** [comment]
I'm using the chrome store release. very cool thanks
