### ISSUE TITLE
Build Error:  unknown file: Property left of AssignmentExpression expected node to be of a type ["LVal"] but instead got "SequenceExpression"

### ISSUE THREAD

**Issue by ritave** [MetaMask/snaps-monorepo#1034]
### Discussed in https://github.com/MetaMask/snaps-monorepo/discussions/1033

<div type='discussions-op-text'>

<sup>Originally posted by **krisbitney** December  2, 2022</sup>
I'm trying to build my Snap and I get this error when trying to import the package I want to use. What are the possible causes of this error? Is it possible to work around it?

I should note that `mm-snap eval` succeeds.

The full error:
```bash
Build error: Failed to post process code:
unknown file: Property left of AssignmentExpression expected node to be of a type ["LVal"] but instead got "SequenceExpression"
<ref *1> Error: Failed to post process code:
unknown file: Property left of AssignmentExpression expected node to be of a type ["LVal"] but instead got "SequenceExpression"
    at postProcessBundle (/Users/kris/WebstormProjects/metamask/Snappy-wraps/node_modules/@metamask/snap-utils/dist/post-process.js:300:15)
    at SnapsBrowserifyTransform._flush (/Users/kris/WebstormProjects/metamask/Snappy-wraps/node_modules/@metamask/snaps-browserify-plugin/dist/plugin.js:98:59)
    at SnapsBrowserifyTransform.final [as _final] (node:internal/streams/transform:112:25)
    at callFinal (node:internal/streams/writable:694:27)
    at prefinish (node:internal/streams/writable:723:7)
    at finishMaybe (node:internal/streams/writable:733:5)
    at SnapsBrowserifyTransform.Writable.end (node:internal/streams/writable:631:5)
    at Labeled.onend (/Users/kris/WebstormProjects/metamask/Snappy-wraps/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (node:events:645:28)
    at Labeled.emit (node:events:538:35) {
  stream: SnapsBrowserifyTransform {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: false,
      ended: false,
      endEmitted: false,
      reading: true,
      constructed: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: true,
      resumeScheduled: false,
      errorEmitted: true,
      emitClose: true,
      autoDestroy: true,
      destroyed: true,
      errored: [Circular *1],
      closed: true,
      closeEmitted: false,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      dataEmitted: false,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: null
    },
    _events: [Object: null prototype] {
      prefinish: [Function: prefinish],
      error: [Function (anonymous)],
      end: [Function],
      readable: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: true,
      needDrain: false,
      ending: true,
      ended: true,
      finished: false,
      destroyed: true,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: true,
      emitClose: true,
      autoDestroy: true,
      errored: [Circular *1],
      closed: true,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    allowHalfOpen: true,
    [Symbol(kCapture)]: false,
    [Symbol(kCallback)]: null
  }
}

```</div>

**Comment by FrederikBolding** [comment]
This is reproducible by assigning to a property called `eval`.
