### ISSUE TITLE
Error when adding snap

### ISSUE THREAD

**Issue by irubido** [MetaMask/snaps-monorepo#1059]
Hi
Got stuck on debugging near-snap, it might be error, I would appreciate an opinion. 
No error while installing, only in extension background.html.

v10.22.2
steps to reproduce the error:

1. git clone https://github.com/ChainSafe/near-snap.git
2. yarn install
3. yarn build
4. yarn serve
5. install from browser dev tools console 
```js
await ethereum.request({
    method: 'wallet_enable',
    params: [{
        wallet_snap: {
            'local:http://localhost:8081': {}
        }
    }],
});
```
extension background.html console error
```
Error when adding snap. Error: Error while running snap 'local:http://localhost:8081': Cannot add property getStackTrace, object is not extensible
  at s._command (background-1.js:1:12978)
  at async s.executeSnap (background-1.js:1:12589)
  at async n.withTimeout (background-1.js:1:57331)
  at async S._executeWithTimeout (background-1.js:1:40294)
  at async S._startSnap (background-1.js:1:34065)
  at async S.processRequestedSnap (background-1.js:1:31270)
  at async background-1.js:1:30027
  at async Promise.all (index 0)
  at async S.installSnaps (background-1.js:1:29767)
  at async r.handleInstallSnaps (background-0.js:3:33579)
  at async implementation (background-0.js:3:34961)
  at async background-5.js:1:128716
```

**Comment by FrederikBolding** [comment]
Hi @irubido 

It looks like your snap is importing a dependency that is trying to modify the `Error` global.

You already have some post-processing for this, but it seems to not catch all the instances:
https://github.com/ChainSafe/near-snap/blob/main/packages/snap/post-process.js

I don't have the full context for your post processing but this may work better?
```
bundleString = bundleString.replaceAll(`Error.captureStackTrace = function `, 'function removed2');
bundleString = bundleString.replaceAll(`Error.getStackTrace = function `, 'function removed1 ');
```

**Comment by irubido** [comment]
> Hi @irubido
> 
> It looks like your snap is importing a dependency that is trying to modify the `Error` global.
> 
> You already have some post-processing for this, but it seems to not catch all the instances: https://github.com/ChainSafe/near-snap/blob/main/packages/snap/post-process.js
> 
> I don't have the full context for your post processing but this may work better?
> 
> ```
> bundleString = bundleString.replaceAll(`Error.captureStackTrace = function `, 'function removed2');
> bundleString = bundleString.replaceAll(`Error.getStackTrace = function `, 'function removed1 ');
> ```

Thanks for quick response and help, yes it didn't catch all the instances of Error in build.
It builds and adds snap without and issue. 
Great help, thank you 👍
