### ISSUE TITLE
MetaMask error reading snap install warnings (undefined map)

### ISSUE THREAD

**Issue by tmpfs** [MetaMask/snaps-monorepo#1073]
Just got this in Flask when attempting to connect to the snap, first time I have seen this:

```
MetaMask encountered an error
Try again by reloading the page, or contact support [here](https://metamask-flask.zendesk.com/hc/en-us/requests/new).
Error details
Message: Cannot read properties of undefined (reading 'map')

Code: TypeError

Stack:
TypeError: Cannot read properties of undefined (reading 'map')
  at flatMap (chrome-extension://caoacbnkhhcdomdibkkdijmmaldbcebo/common-3.js:36952:39)
  at getSnapInstallWarnings (chrome-extension://caoacbnkhhcdomdibkkdijmmaldbcebo/ui-9.js:2132:37)
  at SnapInstall (chrome-extension://caoacbnkhhcdomdibkkdijmmaldbcebo/ui-9.js:1880:53)
  at renderWithHooks (chrome-extension://caoacbnkhhcdomdibkkdijmmaldbcebo/ui-4.js:16267:18)
  at updateFunctionComponent (chrome-extension://caoacbnkhhcdomdibkkdijmmaldbcebo/ui-4.js:18354:20)
  at beginWork$1 (chrome-extension://caoacbnkhhcdomdibkkdijmmaldbcebo/ui-4.js:20183:16)
  at HTMLUnknownElement.callCallback (chrome-extension://caoacbnkhhcdomdibkkdijmmaldbcebo/ui-4.js:343:14)
  at Object.invokeGuardedCallbackDev (chrome-extension://caoacbnkhhcdomdibkkdijmmaldbcebo/ui-4.js:392:16)
  at invokeGuardedCallback (chrome-extension://caoacbnkhhcdomdibkkdijmmaldbcebo/ui-4.js:447:31)
  at beginWork$$1 (chrome-extension://caoacbnkhhcdomdibkkdijmmaldbcebo/ui-4.js:25787:7)
```

**Comment by tmpfs** [comment]
I think this may only occur with `local:` snaps. I have seem some weird behavior with `local:` snaps whereby the state can get wiped out.

For example if I connect to a snap and save some data using `snap_manageState` then come back and try to connect but click cancel, then connect correctly again the state for the snap disappears.

Haven't been able to reproduce this with a snap installed using `npm:`.

**Comment by FrederikBolding** [comment]
Hey @tmpfs!

Are you using MetaMask built locally from `develop` or the Flask version from the Chrome/Firefox store?

The current version released to stores has a bug with certain permissions that trigger this crash. It should be fixed on `develop` and is pending release.

**Comment by FrederikBolding** [comment]
> I assume the fix is after that commit and I should update?

I would think so, yes. Let me know if that does not fix your issue. Then we have something to triage 😅

**Comment by tmpfs** [comment]
I have updated `develop` and assume this is fixed, can re-open if I hit it again. Thanks 🙏
