### ISSUE TITLE
Snap no longer being recognised after installation (using MM extension develop branch)

### ISSUE THREAD

**Issue by tmpfs** [MetaMask/snaps-monorepo#886]
Hi,

I just updated to latest `develop` of the MM extension and now after I go through the snap installation process (successfully) the snap is no longer listed as being installed by the extension and requests that use `snap_manageState` that were working fine before now have a permission denied error.

Is there something I need to update to get this working again or maybe a problem with my local environment?

Flask version: `10.20.0-flask.0`

Built using: `yarn start --build-type flask`
MM develop branch commit hash: 802a20449a4268d6e5d947c420a7351ec6098f5c

Snap ID: `local:${location.protocol}//${location.host}/`

Snap manifest:

```json
{
  "version": "0.1.0",
  "proposedName": "Threshold signatures",
  "description": "Snap for signing ECDSA transactions using threshold signatures.",
  "repository": {
    "type": "git",
    "url": "https://github.com/LavaMoat/demo-gg20-wasm.git"
  },
  "source": {
    "shasum": "hchx+sdrUVvofyCXEXnyXOCLFwyFD0OaTGct8PQ1+54=",
    "location": {
      "npm": {
        "filePath": "bundle.js",
        "iconPath": "images/icon.svg",
        "packageName": "@metamask/mpc-snap",
        "registry": "https://registry.npmjs.org/"
      }
    }
  },
  "initialPermissions": {
    "snap_manageState": {}
  },
  "manifestVersion": "0.1"
}
```

I uploaded a video of the problem if this is not a known issue:

https://s3.ap-southeast-1.amazonaws.com/files.tmpfs.org/snap-install-error.mov

Any pointers much appreciated 🙏

**Comment by Mrtenz** [comment]
Can you take a look in the MetaMask extension background console, after installation? There's likely an issue when installing, and we currently don't provide any feedback about this (working on it though!).

**Comment by tmpfs** [comment]
Nothing really jumps out at me @Mrtenz (maybe `Error with Permissions-Policy header`?):

```
lockdown-install.js:1 Removing intrinsics.Object.hasOwn
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.findLast
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.findLastIndex
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.findLast
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.findLastIndex
lockdown-install.js:1 Removing intrinsics.%StringPrototype%.at
lockdown-install.js:1 Removing intrinsics.%TypedArrayPrototype%.findLast
lockdown-install.js:1 Removing intrinsics.%TypedArrayPrototype%.findLastIndex
chromereload.js:108 WebSocket connection to 'ws://localhost:35729/livereload' failed: 
exports.Connector.Connector.connect @ chromereload.js:108
Connector @ chromereload.js:92
LiveReload @ chromereload.js:352
(anonymous) @ chromereload.js:1124
8../customevents @ chromereload.js:1149
s @ chromereload.js:35
e @ chromereload.js:35
(anonymous) @ chromereload.js:35
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
lockdown-install.js:1 Removing intrinsics.Object.hasOwn
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.findLast
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.findLastIndex
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.findLast
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.findLastIndex
lockdown-install.js:1 Removing intrinsics.%StringPrototype%.at
lockdown-install.js:1 Removing intrinsics.%TypedArrayPrototype%.findLast
lockdown-install.js:1 Removing intrinsics.%TypedArrayPrototype%.findLastIndex
metamask.github.io/phishing-warning/v1.2.1/lockdown-install.js:1 Removing intrinsics.Object.hasOwn
metamask.github.io/phishing-warning/v1.2.1/lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.findLast
metamask.github.io/phishing-warning/v1.2.1/lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.findLastIndex
metamask.github.io/phishing-warning/v1.2.1/lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.findLast
metamask.github.io/phishing-warning/v1.2.1/lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.findLastIndex
metamask.github.io/phishing-warning/v1.2.1/lockdown-install.js:1 Removing intrinsics.%StringPrototype%.at
metamask.github.io/phishing-warning/v1.2.1/lockdown-install.js:1 Removing intrinsics.%TypedArrayPrototype%.findLast
metamask.github.io/phishing-warning/v1.2.1/lockdown-install.js:1 Removing intrinsics.%TypedArrayPrototype%.findLastIndex
metamask.github.io/phishing-warning/v1.2.1/bundle.js:17 Service worker registered!
DevTools failed to load source map: Could not load content for https://metamask.github.io/phishing-warning/v1.2.1/bundle.js.map: Fetch through target failed: Session is unregistering, can't dispatch pending call to Network.loadNetworkResource; Fallback: Unknown error
chromereload.js:108 WebSocket connection to 'ws://localhost:35729/livereload' failed: 
exports.Connector.Connector.connect @ chromereload.js:108
(anonymous) @ chromereload.js:89
(anonymous) @ chromereload.js:1163
chromereload.js:108 WebSocket connection to 'ws://localhost:35729/livereload' failed: 
exports.Connector.Connector.connect @ chromereload.js:108
(anonymous) @ chromereload.js:89
(anonymous) @ chromereload.js:1163
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
lockdown-install.js:1 Removing intrinsics.Object.hasOwn
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.findLast
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.findLastIndex
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.findLast
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.findLastIndex
lockdown-install.js:1 Removing intrinsics.%StringPrototype%.at
lockdown-install.js:1 Removing intrinsics.%TypedArrayPrototype%.findLast
lockdown-install.js:1 Removing intrinsics.%TypedArrayPrototype%.findLastIndex
inpage.js:3162 MetaMask: Connected to chain with ID "0x5".
chromereload.js:108 WebSocket connection to 'ws://localhost:35729/livereload' failed: 
exports.Connector.Connector.connect @ chromereload.js:108
(anonymous) @ chromereload.js:89
(anonymous) @ chromereload.js:1163
chromereload.js:108 WebSocket connection to 'ws://localhost:35729/livereload' failed: 
exports.Connector.Connector.connect @ chromereload.js:108
(anonymous) @ chromereload.js:89
(anonymous) @ chromereload.js:1163
bundle.js:373 MetaMask < = > Ledger Bridge initialized from https://metamask.github.io/eth-ledger-bridge-keyring/!
chromereload.js:108 WebSocket connection to 'ws://localhost:35729/livereload' failed: 
exports.Connector.Connector.connect @ chromereload.js:108
(anonymous) @ chromereload.js:89
(anonymous) @ chromereload.js:1163
chromereload.js:108 WebSocket connection to 'ws://localhost:35729/livereload' failed: 
exports.Connector.Connector.connect @ chromereload.js:108
(anonymous) @ chromereload.js:89
(anonymous) @ chromereload.js:1163
```

**Comment by FrederikBolding** [comment]
@tmpfs Hmm, this doesn't look like it includes any snap installation? That would log a bit of information as it processes the installation 🤔

**Comment by tmpfs** [comment]
My bad @FrederikBolding, this looks like the culprit:

```
SnapController.js:908 Adding snap: local:http://localhost:7070/
SnapController.js:1139 Authorizing snap: local:http://localhost:7070/
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
lockdown-install.js:1 Removing intrinsics.Object.hasOwn
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.findLast
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.findLastIndex
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.findLast
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.findLastIndex
lockdown-install.js:1 Removing intrinsics.%StringPrototype%.at
lockdown-install.js:1 Removing intrinsics.%TypedArrayPrototype%.findLast
lockdown-install.js:1 Removing intrinsics.%TypedArrayPrototype%.findLastIndex
inpage.js:3162 MetaMask: Connected to chain with ID "0x5".
bundle.js:2 Worker: Connecting to parent.
AbstractExecutionService.js:220 Parent: Sending Command {jsonrpc: '2.0', method: 'ping', id: 'GK9_kvWlfdHW_5HrLOl09'}
AbstractExecutionService.js:220 Parent: Sending Command {jsonrpc: '2.0', method: 'executeSnap', params: {…}, id: 'kfZUuORdHMLFl5gGMPZ5c'}
metamask.github.io/iframe-execution-environment/0.9.1/bundle.js:2 starting snap 'local:http://localhost:7070/' in worker
AbstractExecutionService.js:220 Parent: Sending Command {jsonrpc: '2.0', method: 'terminate', params: Array(0), id: 'RoDf-ER80H0BAdN5TB5wh'}
AbstractExecutionService.js:77 Job "6kz3Cby5LfDG_sUa53-G6" terminated.
SnapController.js:801 Error when adding snap. Error: Error while running snap 'local:http://localhost:7070/': wallet.registerRpcMessageHandler is not a function
  at IframeExecutionService._command (AbstractExecutionService.js:223:1)
  at async IframeExecutionService.executeSnap (AbstractExecutionService.js:203:1)
  at async withTimeout (utils.js:85:1)
  at async SnapController._executeWithTimeout (SnapController.js:1283:1)
  at async SnapController._startSnap (SnapController.js:939:1)
  at async SnapController.processRequestedSnap (SnapController.js:792:1)
  at async SnapController.js:726:1
  at async Promise.all (index 0)
  at async SnapController.installSnaps (SnapController.js:714:1)
  at async handleInstallSnaps (snapInstallation.js:80:1)
processRequestedSnap @ SnapController.js:801
await in processRequestedSnap (async)
(anonymous) @ SnapController.js:726
await in (anonymous) (async)
installSnaps @ SnapController.js:714
(anonymous) @ SnapController.js:205
call @ ControllerMessenger.js:251
handleInstallSnaps @ snapInstallation.js:80
enableWallet @ enable.js:111
await in enableWallet (async)
methodMiddleware @ createMethodMiddleware.js:94
(anonymous) @ JsonRpcEngine.js:215
_runMiddleware @ JsonRpcEngine.js:189
_runAllMiddleware @ JsonRpcEngine.js:175
await in _runAllMiddleware (async)
_processRequest @ JsonRpcEngine.js:149
_handle @ JsonRpcEngine.js:127
handle @ JsonRpcEngine.js:37
write @ engineStream.js:20
doWrite @ _stream_writable.js:428
writeOrBuffer @ _stream_writable.js:417
Writable.write @ _stream_writable.js:334
ondata @ _stream_readable.js:619
emitOne @ events.js:106
emit @ events.js:184
addChunk @ _stream_readable.js:291
readableAddChunk @ _stream_readable.js:278
Readable.push @ _stream_readable.js:245
_write @ index.js:68
doWrite @ _stream_writable.js:428
writeOrBuffer @ _stream_writable.js:417
Writable.write @ _stream_writable.js:334
ondata @ _stream_readable.js:619
emitOne @ events.js:106
emit @ events.js:184
addChunk @ _stream_readable.js:291
readableAddChunk @ _stream_readable.js:278
Readable.push @ _stream_readable.js:245
_onMessage @ index.js:26
(anonymous) @ index.js:11
createLoggerMiddleware.js:17 Error in RPC response:
 {id: 640626253, jsonrpc: '2.0', error: {…}}
(anonymous) @ createLoggerMiddleware.js:17
(anonymous) @ JsonRpcEngine.js:229
_runReturnHandlers @ JsonRpcEngine.js:228
await in _runReturnHandlers (async)
_processRequest @ JsonRpcEngine.js:155
await in _processRequest (async)
_handle @ JsonRpcEngine.js:127
handle @ JsonRpcEngine.js:37
write @ engineStream.js:20
doWrite @ _stream_writable.js:428
writeOrBuffer @ _stream_writable.js:417
Writable.write @ _stream_writable.js:334
ondata @ _stream_readable.js:619
emitOne @ events.js:106
emit @ events.js:184
addChunk @ _stream_readable.js:291
readableAddChunk @ _stream_readable.js:278
Readable.push @ _stream_readable.js:245
_write @ index.js:68
doWrite @ _stream_writable.js:428
writeOrBuffer @ _stream_writable.js:417
Writable.write @ _stream_writable.js:334
ondata @ _stream_readable.js:619
emitOne @ events.js:106
emit @ events.js:184
addChunk @ _stream_readable.js:291
readableAddChunk @ _stream_readable.js:278
Readable.push @ _stream_readable.js:245
_onMessage @ index.js:26
(anonymous) @ index.js:11
```

**Comment by tmpfs** [comment]
Has the API for registering snaps changed now? My code looks like this:

```javascript
wallet.registerRpcMessageHandler(async (originString, requestObject) => {
  console.log("Snap running...");

  switch (requestObject.method) {
    case "getState":
      return wallet.request({
        method: "snap_manageState",
        params: ["get"],
      });
    case "updateState":
      return wallet.request({
        method: "snap_manageState",
        params: ["update", requestObject.params],
      });
    case "clearState":
      return wallet.request({
        method: "snap_manageState",
        params: ["clear"],
      });
    default:
      throw new Error("Method not found.");
  }
});
```

**Comment by FrederikBolding** [comment]
Yes, it has!

Snaps now use exports to expose functionality instead of callbacks. See https://github.com/MetaMask/template-snap-monorepo/blob/main/packages/snap/src/index.ts#L23

**Comment by tmpfs** [comment]
Thanks @FrederikBolding!

**Comment by tmpfs** [comment]
Thanks @ritave, i was wondering where i should look for that info 🙏
